package Acme::CPANLists::Import::PerlDancerAdvent::2012;

# DATE
# VERSION

our @Module_Lists = ({description=>"This list is generated by extracting module names mentioned in [http://advent.perldancer.org/2012/] (retrieved on 2016-11-24). Visit the URL for the full contents.",entries=>[{module=>"App::Wallflower"},{module=>"Dancer::Plugin::Auth::Extensible"},{module=>"Dancer::Plugin::CDN"},{module=>"Dancer::Plugin::DictionaryCheck"},{module=>"Dancer::Plugin::EmptyGIF"},{module=>"Dancer::Plugin::I18N"},{module=>"Dancer::Plugin::Res"},{module=>"HTTP::CDN"},{module=>"HTTP::Headers"},{module=>"Locale::Maketext::Simple"},{module=>"Crypt::SaltedHash"},{module=>"Dancer::Plugin::Auth::Extensible::Provider::Base"},{module=>"Dancer::Plugin::Auth::RBAC"},{module=>"Dancer::Plugin::DBIC"},{module=>"Dancer::Plugin::Database"},{module=>"Dancer"},{module=>"Starman"},{module=>"Moo"},{module=>"Template"},{module=>"Dancer::Template::Mustache"},{module=>"Dancer::Plugin::SimpleCRUD"},{module=>"HTML::Table::FromDatabase"},{module=>"Dancer::Plugin"},{module=>"Pod::Simple"},{module=>"Sphinx::Search"},{module=>"Devel::Cover"},{module=>"Dancer::Plugin::Stomp"},{module=>"Dancer::Plugin::Ajax"},{module=>"Dancer::Template::Mason"},{module=>"Mason"},{module=>"Plack"},{module=>"DBD::SQLite"},{module=>"DBI"},{module=>"File::Slurp"},{module=>"Math::Base36"},{module=>"Bread::Board"},{module=>"Dancer::Plugin::Adapter"},{module=>"WWW::Postmark"}],summary=>"Modules mentioned in PerlDancer Advent Calendar 2012"});

1;
# ABSTRACT: Modules mentioned in PerlDancer Advent Calendar 2012

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<http://advent.perldancer.org/2012/> (retrieved on 2016-11-24). Visit the URL for the full contents.

