package Acme::CPANLists::Import::PerlDancerAdvent::2012_12_03;

# DATE
# VERSION

our @Module_Lists = ({description=>"This list is generated by extracting module names mentioned in [http://advent.perldancer.org/2012/3] (retrieved on 2016-11-24). Visit the URL for the full contents.",entries=>[{module=>"Dancer"},{module=>"Starman"}],summary=>"Modules mentioned in PerlDancer Advent Calendar 2012 (day 3)"});

1;
# ABSTRACT: Modules mentioned in PerlDancer Advent Calendar 2012 (day 3)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<http://advent.perldancer.org/2012/3> (retrieved on 2016-11-24). Visit the URL for the full contents.

