package Acme::CPANLists::Import::PerlDancerAdvent::2012_12_01;

# DATE
# VERSION

our @Module_Lists = ({description=>"This list is generated by extracting module names mentioned in [http://advent.perldancer.org/2012/1] (retrieved on 2016-11-24). Visit the URL for the full contents.",entries=>[{module=>"App::Wallflower"},{module=>"Dancer::Plugin::Auth::Extensible"},{module=>"Dancer::Plugin::CDN"},{module=>"Dancer::Plugin::DictionaryCheck"},{module=>"Dancer::Plugin::EmptyGIF"},{module=>"Dancer::Plugin::I18N"},{module=>"Dancer::Plugin::Res"},{module=>"HTTP::CDN"},{module=>"HTTP::Headers"},{module=>"Locale::Maketext::Simple"}],summary=>"Modules mentioned in PerlDancer Advent Calendar 2012 (day 1)"});

1;
# ABSTRACT: Modules mentioned in PerlDancer Advent Calendar 2012 (day 1)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<http://advent.perldancer.org/2012/1> (retrieved on 2016-11-24). Visit the URL for the full contents.

