package Acme::CPANLists::Import::PerlDancerAdvent::2012_12_02;

# DATE
# VERSION

our @Module_Lists = ({description=>"This list is generated by extracting module names mentioned in [http://advent.perldancer.org/2012/2] (retrieved on 2016-11-24). Visit the URL for the full contents.",entries=>[{module=>"Crypt::SaltedHash"},{module=>"Dancer::Plugin::Auth::Extensible"},{module=>"Dancer::Plugin::Auth::Extensible::Provider::Base"},{module=>"Dancer::Plugin::Auth::RBAC"},{module=>"Dancer::Plugin::DBIC"},{module=>"Dancer::Plugin::Database"}],summary=>"Modules mentioned in PerlDancer Advent Calendar 2012 (day 2)"});

1;
# ABSTRACT: Modules mentioned in PerlDancer Advent Calendar 2012 (day 2)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<http://advent.perldancer.org/2012/2> (retrieved on 2016-11-24). Visit the URL for the full contents.

