#!/usr/bin/env perl

use 5.010;
use strict;
use warnings;
use FindBin '$Bin';

use App::CreateAcmeCPANListsImportModules;
use Perinci::Sub::Util qw(gen_curried_sub);
use Perinci::CmdLine::Any;

my @days = (1..8, 11, 14, 16, 17, 18, 21..24);

gen_curried_sub(
    'App::CreateAcmeCPANListsImportModules::create_acme_cpanlists_import_modules',
    {
        modules => [
            {
                name => '2012',
                url => "http://advent.perldancer.org/2012/",
                extract_urls => [map {"http://advent.perldancer.org/2012/$_"} @days],
                summary => 'Modules mentioned in PerlDancer Advent Calendar 2012',
            },
            (map {
                +{
                    name => sprintf("2012_12_%02d", $_),
                    url => "http://advent.perldancer.org/2012/$_",
                    summary => "Modules mentioned in PerlDancer Advent Calendar 2012 (day $_)",
                } } @days),
        ],
        namespace => 'Acme::CPANLists::Import::PerlDancerAdvent',
        user_agent => 'Mozilla/5.0',
        dist_dir => "$Bin/..",
    },
    'app',
);

Perinci::CmdLine::Any->new(
    url => '/main/app',
    log => 1,
)->run;
